version: "3.8"

services:
  web:
    image: rodperoba/emailgpt:v0.1
    build:
      context: ..
      dockerfile: DockerFolder/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ../Backend/uploads:/app/uploads
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - API_KEY=${API_KEY}
    env_file:
      - .env
    restart: unless-stopped
