version: "3.8"

services:
  web:
    build:
      context: ..
      dockerfile: DockerFolder/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ../Backend/uploads:/app/uploads
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
    env_file:
      - .env
    restart: unless-stopped
