version: "3.8"

services:
  web:
    build:
      context: ../.. # Aponta para o diretório raiz do projeto
      dockerfile: MainFolder/DockerFolder/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ../Backend/uploads:/app/uploads
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - API_KEY=sua_chave
